title: Kajal | Developer Portfolio
description: Kajal learning portfolio and project documentation.
url: https://r14r.github.io
baseurl: /Kajal_CV
markdown: kramdown
permalink: pretty
exclude:
  - README.md
